name: Daily Notification Triggers

on:
  schedule:
    # Morning motivation at 8:00 AM UTC (adjust timezone as needed)
    - cron: '0 8 * * *'
    # Afternoon check-in at 2:00 PM UTC (adjust timezone as needed)  
    - cron: '0 14 * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:
    inputs:
      notification_type:
        description: 'Which notification to trigger'
        required: true
        default: 'both'
        type: choice
        options:
        - morning
        - afternoon
        - both

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Set notification type for schedule
        id: set-type
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            hour=$(date -u +"%H")
            if [ "$hour" = "08" ]; then
              echo "type=morning" >> $GITHUB_OUTPUT
            elif [ "$hour" = "14" ]; then
              echo "type=afternoon" >> $GITHUB_OUTPUT
            else
              echo "type=none" >> $GITHUB_OUTPUT
            fi
          else
            echo "type=${{ github.event.inputs.notification_type }}" >> $GITHUB_OUTPUT
          fi

      - name: Trigger Morning Motivation
        if: steps.set-type.outputs.type == 'morning' || steps.set-type.outputs.type == 'both'
        run: |
          response=$(curl -s -w "%{http_code}" -o response.txt \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json" \
            https://xhmzmzynshesqpxienfb.supabase.co/functions/v1/Morning-motiviation)
          echo "HTTP Status: $response"
          echo "Response:"
          cat response.txt
          if [ $response -ne 200 ]; then
            echo "Morning notification failed with status $response"
            exit 1
          fi

      - name: Trigger Afternoon Check-in
        if: steps.set-type.outputs.type == 'afternoon' || steps.set-type.outputs.type == 'both'
        run: |
          response=$(curl -s -w "%{http_code}" -o response.txt \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json" \
            https://xhmzmzynshesqpxienfb.supabase.co/functions/v1/Afternoon-Checkin)
          echo "HTTP Status: $response"
          echo "Response:"
          cat response.txt
          if [ $response -ne 200 ]; then
            echo "Afternoon notification failed with status $response"
            exit 1
          fi