name: Manual Notification

on:
  workflow_dispatch:
    inputs:
      notification_type:
        description: 'Which notification to trigger'
        required: true
        default: 'both'
        type: choice
        options:
        - morning
        - afternoon
        - both

jobs:
  manual-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Morning Motivation
        if: ${{ github.event.inputs.notification_type == 'morning' || github.event.inputs.notification_type == 'both' }}
        run: |
          response=$(curl -s -w "%{http_code}" -o response.txt \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json" \
            https://xhmzmzynshesqpxienfb.supabase.co/functions/v1/Morning-motiviation)
          echo "HTTP Status: $response"
          echo "Response:"
          cat response.txt
          if [ $response -ne 200 ]; then
            echo "Morning notification failed with status $response"
            exit 1
          fi

      - name: Trigger Afternoon Check-in
        if: ${{ github.event.inputs.notification_type == 'afternoon' || github.event.inputs.notification_type == 'both' }}
        run: |
          response=$(curl -s -w "%{http_code}" -o response.txt \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json" \
            https://xhmzmzynshesqpxienfb.supabase.co/functions/v1/Afternoon-Checkin)
          echo "HTTP Status: $response"
          echo "Response:"
          cat response.txt
          if [ $response -ne 200 ]; then
            echo "Afternoon notification failed with status $response"
            exit 1
          fi 